Add EXPOSE lines to Dockerfile
linuxserver/docker-domoticz pull request #95
Opened 2021-04-30 07:47 UTC by Frank071

See https://github.com/linuxserver/docker-domoticz/issues/94

2021-05-03 13:26 UTC, tobbenb requested changes
Please add all ports on one line

2021-05-03 13:28 UTC, aptalca commented
and to all dockerfiles

2021-05-03 15:02 UTC, Frank071 commented
> Please add all ports on one line

I didn't because the Docker documentation is not clear on this. More specifically, when describing exposing a port on tcp and udp, it explicitly states:
```
To expose on both TCP and UDP, include two lines:
  EXPOSE 80/tcp
  EXPOSE 80/udp
```
All on one line seems possible (I see from other sources) so I'll update
 
> and to all dockerfiles

I see what you mean. Will do.

2021-05-22 13:34 UTC, Roxedus approved these changes

2021-05-22 13:35 UTC, merged